### ISSUE TITLE
After creating a fiscal data schema, one should be able to add resources by clicking on `Edit fiscal data schema`

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#149]
When I click on `Create a fiscal data schema` in the dashboard and I create a new dataset, I want to be able to go back to the dashboard and add new resources to the dataset I just created so I can upload all the resources that are part of my dataset.

## Acceptance

* [x] Once a dataset has been created after adding a resource with the `Create a fiscal data schema` flow, a user should be able to click on `Edit fiscal data schema` for the same dataset to add new resources.

**Done** This issue has been fixed in the latest deployed version of Portal. For reference, see this pull https://github.com/datopian/gift-portal/pull/154

The issue was caused by not using ES6 promises in our API calls, this made tracking of upload/saving state inconsistent. 

## Analysis

* There is a delay for pushing updates to GitHub which can range from a few seconds (_sometimes_) to more than 30 minutes (maximum delay to be confirmed, but usually at least 10 minutes in our latest tests). This prevents users from adding new resources to an existing dataset.

**Comment by risenW** [comment]
BLOCKED: See https://github.com/datopian/gift-portal/issues/150#issuecomment-784221051

**Comment by risenW** [comment]
FIXED: This issue has been fixed in the latest deployed version of Portal. For reference, see this pull https://github.com/datopian/gift-portal/pull/154

The issue was caused by not using ES6 promises in our API calls, this made tracking of upload/saving state inconsistent.

**Comment by sglavoie** [comment]
@risenW, could you please see whether you can access a dataset from the dashboard that you would have created recently (<10 minutes before trying)? I can't see the logs on Vercel (free plan, so I'm no longer able to access them...) and the repo I've created ~20 minutes ago is still not showing up in the dashboard of the portal: https://github.com/gift-data/test-github-actions

Do you think there's anything related to this GitHub delay issue we've been having? This is a bit the same situation in which a user can't add resources to a dataset (although here the issue is that the dataset isn't shown at all in the dashboard).
